#!/bin/bash
#Script to add .bak to any file

#Creating functions

#cpSameDir  - Run when making backup in same directory. Copies file name, appends .bak, and then confirms that the file was copied.
function cpSameDir
{
		cp $x $x.bak
		echo "Backed up $x as $x.bak"
}

function quitProgram
{
		echo "Quitting!"
		break
}

function cpDiffDir
{
		cp $x $userInput\/$x.bak
		echo "Backed up $x as $x.bak in $userInput"
}

function enterFileName
{
echo "Enter a filename to backup. If you don't wish to enter anything, please type QUIT > "
read filename

}

function earlyQuit
{
if [ "$filename" == "QUIT" ]; then
	echo "Quitting!"
	exit
fi
}
##### Begin Program #####

#This calls function above to request file name.
enterFileName

#This lets user quit before doing anything else. Rather than risk altering a file.
earlyQuit

#This will specify the directory
echo "Enter the directory you wish to back up to. Just press ENTER if you are backing up to the current directory. If you'd like to quit, enter QUIT."
read userInput

#This takes the filename as input, and accepts any argument made in filename as x. If enter is pressed, it makes a backup in current directory. If QUIT is entered, nothing happens. If a directory is specified, then it copies that file to that directory.
for x in $filename
do
	if [ "$userInput" == "" ]; then
		cpSameDir
	elif [ "$userInput" == "QUIT" ]; then
		quitProgram
	else
		cpDiffDir
	fi
done
